name: RDP with Ngrok

on: [push]

jobs:
  rdp:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Ngrok
        run: |
          curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
          unzip ngrok-stable-darwin-amd64.zip

      - name: Authenticate Ngrok
        run: ./ngrok authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok Tunnel
        run: ./ngrok tcp 3389
